name: Build and Test QKO

on:
    push:
        branches:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: ./.github/workflows/setup-build-test.yml

            - name: Build
              run: ./gradlew build

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - uses: ./.github/workflows/setup-build-test.yml

            - name: Test
              run: ./gradlew test
