name: Build and Test QKO

on:
    push:
        branches:
            - '*'

jobs:
    setup:
        runs-on: ubuntu-latest
        steps: &setup-steps
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 21

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v3

    build:
        runs-on: ubuntu-latest
        needs: setup

        steps:
            - *setup-steps

            - name: Build
              run: ./gradlew build

    test:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - *setup-steps

            - name: Test
              run: ./gradlew test
