name: (Reusable Workflow) Publish packages
on:
    workflow_call:
        inputs:
            env:
                type: string
                description: 'Set as production to publish your artifacts'
                default: 'test'
            actor:
                type: string
                description: 'Your github username'
                required: true
        secrets:
            GPG_KEY:
                description: 'Your private GPG KEY'
                required: true
            GPG_PASSWORD:
                description: 'Your GPG KEY passphrase'
                required: true
            GPG_KEYID:
                description: 'Your GPG KEY last 8 digits'
                required: true
            GH_TOKEN:
                description: 'Your secret GITHUB_TOKEN'
                required: true

jobs:
    publish_github:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: setup key
              run: |
                  chmod +x ./ci-utils/setup-gpg.sh
                  ./ci-utils/setup-gpg.sh
              env:
                  GPG_KEY: ${{ secrets.GPG_KEY }}
                  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}

            - uses: gradle/actions/setup-gradle@v3

            # check out: https://docs.gradle.org/current/userguide/signing_plugin.html
            - name: Setup Gradle Signing
              run: gradle sign -Psigning.secretKeyRingFile=../../../.gnupg/secring.gpg -Psigning.password=${{ secrets.GPG_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_KEYID }}

            - name: Publish
              if: ${{ inputs.env == 'production' }}
              run: ./gradlew publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
                  GITHUB_ACTOR: ${{ inputs.actor }}
