name: (Reusable Workflow) Publish packages
on:
    workflow_call:
        inputs:
            env:
                type: string
                description: 'Set as production to publish your artifacts'
                default: 'test'
        secrets:
            GPG_KEY:
                description: 'Your private GPG KEY'
                required: true
            GPG_PASSWORD:
                description: 'Your GPG KEY passphrase'
                required: true
            GPG_KEYID:
                description: 'Your GPG KEY last 8 digits'
                required: true
            OSSRH_USERNAME:
                description: 'Your Maven Central Key Username'
                required: true
            OSSRH_PASSWORD:
                description: 'Your Maven Central Key password'
                required: true

jobs:
    publish:
        runs-on: ubuntu-24.04

        env:
            GPG_DIR: ~/.gnupg
            GPG_SECRING_FILE_PATH: ~/.gnupg/secring.gpg

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: setup key
              run: |
                  chmod +x ./ci-utils/setup-gpg.sh
                  ./ci-utils/setup-gpg.sh
              env:
                  GPG_KEY: ${{ secrets.GPG_KEY }}
                  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}

            - uses: gradle/actions/setup-gradle@v3

            - name: Publish
              if: ${{ inputs.env == 'production' }}
              run: |
                  export GPG_KEY=$(cat $GPG_SECRING_FILE_PATH)
                  ./gradlew publish --info --stacktrace
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ACTOR: ${{ github.actor }}
                  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  GPG_KEY_PASSWORD: ${{ secrets.GPG_PASSWORD }}
