name: (Test) Publish packages Setup
on:
    push:
        branches:
            - 'test-actions'
jobs:
    publish_github:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: setup key
              run: |
                  chmod +x ./ci-utils/setup-gpg.sh
                  ./ci-utils/setup-gpg.sh

            - uses: gradle/actions/setup-gradle@v3

            - name: Setup Gradle Signing
              run: gradle sign -Psigning.secretKeyRingFile=../../../.gnupg/secring.gpg -Psigning.password=${{ secrets.GPG_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_KEYID }}
