name: (Test) Publish packages Setup
on:
    push:
        branches:
            - 'test-actions'
jobs:
    publish_github:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: setup key
              run: |
                  sudo apt-get update && sudo apt-get install -y gnupg
                  mkdir -p ~/.gnupg
                  chmod 700 ~/.gnupg
                  if [ ! -f ~/.gnupg/gpg.conf ]; then touch ~/.gnupg/gpg.conf; fi
                  if [ ! -f ~/.gnupg/gpg-agent.conf ]; then touch ~/.gnupg/gpg-agent.conf; fi
                  echo "use-agent" >> ~/.gnupg/gpg.conf
                  echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
                  echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
                  echo RELOADAGENT | gpg-connect-agent
                  cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
                  gpg --batch --no-tty --export-secret-keys --output ~/.gnupg/secring.gpg

            - uses: gradle/actions/setup-gradle@v3

            - name: Setup Gradle Signing
              run: gradle sign -Psigning.secretKeyRingFile=~/.gnupg/secring.gpg -Psigning.password=${{ secrets.GPG_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_KEYID }}
