name: Release and Publish packages
on:
    push:
        tags:
            - '*'
jobs:
    release:
        runs-on: ubuntu-24.04
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: create release
              uses: ncipollo/release-action@v1

    publish:
        runs-on: ubuntu-24.04
        needs: release

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - uses: gradle/actions/setup-gradle@v3

            - name: Publish
              run: ./gradlew publish --info --stacktrace
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ACTOR: ${{ github.actor }}
