name: Release and Publish packages
on:
    push:
        tags:
            - '*'
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: create release
              uses: ncipollo/release-action@v1

    publish_github:
        needs: release

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Publish package
              run: mvn --batch-mode deploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
