name: Release and Publish packages
on:
    push:
        tags:
            - '*'
jobs:
    release:
        runs-on: ubuntu-24.04
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: create release
              uses: ncipollo/release-action@v1

    publish:
        needs: release
        permissions:
            contents: read
            packages: write

        uses: ./.github/workflows/publish.yml
        secrets:
            GPG_KEY: ${{ secrets.GPG_KEY }}
            GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
            GPG_KEYID: ${{ secrets.GPG_KEYID }}
        with:
            env: 'production'
