name: Release and Publish packages
on:
    push:
        tags:
            - '*'
jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - name: create release
              uses: ncipollo/release-action@v1

    publish_github:
        needs: release

        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: setup key
              run: |
                  cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
                  gpg --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg

            - uses: gradle/actions/setup-gradle@v3

            - name: Setup Gradle Signing
              run: gradle sign -Psigning.secretKeyRingFile=~/.gnupg/secring.gpg -Psigning.password=${{ secrets.GPG_PASSWORD }} -Psigning.keyId=${{ secrets.GPG_KEYID }}

            - name: Publish package
              run: ./gradlew publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_ACTOR: ${{ github.actor }}
